version: '3'

services:
  message_db_test_db:
    image: postgres:10.6
    environment:
      - POSTGRES_DB=message_db_test_db
    ports:
      - '0.0.0.0:5432:5432'
  message-db:
    image: wolfejw86/pg-message-db:latest
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '0.0.0.0:5433:5432'
